name: appassesment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #----- State Management -----#
  get: ^4.6.6
  #----- Network -----#
  dio: ^5.4.3+1
  #----- UI -----#
  flutter_svg: ^2.0.10+1
  otp_text_field: ^1.1.3
  #----- Utils -----#
  otp_autofill: ^3.0.2
  shared_preferences: ^2.2.3
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/metropolis_regular.otf
          weight: 400
    - family: sm_bold
      fonts:
        - asset: assets/fonts/metropolis_semi_bold.otf
          weight: 600
    - family: xs_light
      fonts:
        - asset: assets/fonts/metropolis_light.otf
          weight: 600
    - family: sm_medium
      fonts:
        - asset: assets/fonts/metropolis_medium.otf
          weight: 500
